"""
Django settings for my_django_project project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import redis
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@kx-4=m^i28%93+%lia+e(ck!ev23mhj1ipvsv*r&hygc$wu-3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['djangoproject.localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    "corsheaders",
    'rest_framework',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.SafeJWTAuthentication',
    )
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'my_django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_django_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'apache_server',
        'USER': 'root',
        'PASSWORD': 'password',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}

from datetime import timedelta

PKEY = """-----BEGIN PRIVATE KEY-----
MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQDIIXOrs5nDBt6f
OVWS8jqPAx+vSXDOtmWVTU4kzSrIVgFe5zTXC03efc8c18DCWt7zip6zI1nh68GJ
qiy2ARrPdtPKM7+R3DGc+PVudW1QtCvAU9K1AO2JVkIhXiRdM4CrJBSLWhkITD0y
cKC/+45qbVVRFpY8B3XMopKUh1taHaxjzNRu9btZGVhtw07pICuhQo0bMuMtdilP
/sFGsKuWAQEecuN7L5WHHctsYU5cguntHbRKBMMnwDDiudpx+00Zeoz0UAULxYx5
HiSq+/kQOvx97pBk4wtNh5dN1bpCFYJp+bE3pTCT4Vzc4ocFwOhabj2utrMTboQP
0PrK2MlFMCSOS0R1oK9WiJWHPNF6RdwNxg84SrYrBLq0GpQ4x1HSwak0Gf/IWXHj
a/FTWy4JSkR9DmL4hYaQb7Yf3mUXQbP9uNR83FSYQhkJfgBFR93cIkqhvS/2m81o
lJBUh7vwlteMvdiwj3XRg0rWVMFvVsfz2A9aTcSpS8W529oipRUyy+UD8k/1LpOx
4Ps7fYIYxPBvW9QpBRlkg9WP7Co/674uL26+SayNA5VMh2I0j+RUPChYSBwJGJqX
2vtEFbcmLTNMzKao+kym5TzvqLjOcCRajrmbCEmCjHQMtxquPOFP6u+RxXIfgRfV
Hn2zlay0EHzrc3oDmK0Cal2/g42h0QIDAQABAoICAC9UtgIQJlfZCpKWoTXxIsdK
4lX25P6GZazzTP1oJmud55IV1UnciwyJLY/xOM3eZucrTBAq1qmXM70Gqa9bwIb7
X+hs56wr6vHocUcv72wMSGKikG0tbIA0DczNcoU2VoJjNJamdtAfE8QXnfT5nftu
oyRb1qkYzJPaiRcmkgTUir5JpZ4ecLIITAEdlU6ORLNNRYj+tnq8fNXF9tjslJAT
6btVSZaLMO51LfSSaNF5RrDE+ywcRzlh+03Lza1yVRAnCyoGuMLJdEj6x4pGsGdV
w/xWjQDHL5ek7zRBzVyusJq2qmJyJ3R58pfs3SkPsAQfGWh2HhEE7Ke+8WlC7wqK
FYi7Xnlydneu5V7rg0JZuG0tuCaHe0hsTQj9vOcY5HLxMw+MYxJRUyb4H7e89fMY
0ZwVJQGt7kbwpZE9EenyOtkS98TxQv2x/CSC2dU+jBDk/48ElID9prjl8/TfNb03
TuvGdcLvFniKFYubAFlcVNcKjZlfnPh9lv7ABlUrSfIdS3x39ja96U+rd/i3wXij
+ahAxZXvXgll8tLxBHNticbmJmxuPVwTqsDzEu/0eCmDrcRkqtkIYpuFTul/EIlG
YvX/hgdtEkhF+hGenb9xZr++docSGWUmYNC1OmxrkFSjNHNB9CR+i2u0j1zfQlcC
4q/34JhDmpl79z3qOreXAoIBAQDSIZCYTT7G7T5PGhY5A5BQ4HmhPJ2IENAM/GXt
ZQgSDPvmAel3UCyAlly/1SdjCpxI0G+j53f1VyUfLraJe0B7lXN6PbbKff4wLuO+
t4Egl11aBpWM4b40gH/43MpQify3AgjQzDKOuch+Fd5+NV2ZrTkgA6FAAKPhriDI
QF8T0qyyzgz/v3iGrQ3dhviuFjk5TM+MVvh6ciSZ5HLZbcS6LFhemiOCzLF8y+QX
PGbOklaSMUPx0hzHPJY75hGPKyJQ66b0+XiMperhE7ilZsbON2eI992g1JBU8wDK
cjhViVVdfBn5L9aGz//dKYwKOtpz69jEppg7HdgwThTQmjUrAoIBAQDz0Qwzys/v
s7TJyZF9ERTG2NzBxmtdFG50vf639YZqmsUbwS1kw1WlDbLmPMLrnZta8gjtbu17
vx/iXNmTn+sagZ5S0w+eLFctiptcyioYovChbXq5Yp4C7vPpNUoYXWz7Y8v3IbFu
E44Ppvzd20Ta0qT+NupHNpZWwFwOMKguSChYcA0Y42fNL7m+qw1K4Vui0tmSCH74
xTb6gz0ApN8enyYQKqN4Xa86d09aJB5ZiTCYfn+UsWerLrh+yzjzcNTQZGnarp5i
513gEQIVD79aZ7+PsxByo6BbEKY20NEK90lvfyM51QUbi+s5ANIeVyV6JqRb2nYf
bx8E6CcUBn7zAoIBAFkeeSfO4wgVSG7d/nzRwRw8B/nVLm6tyr8nMMd9KO4W6aLE
PtMmgqlKnC2T5m9/6YaMOD0Ih3zbJ9hQxIQMbO29FcvLbsH0q6Cd0mNpim9bIvFy
h2zHtRapRR0z7u43h6HKUBjV8b9Mlfa7qbBXS8pIiEjGoVX2r4qggjDL9EcA+9Od
xi+VcjWUIaRJgSC8NirSI9g+boXn8RP/qqIChwP6mMQOlW79B22JP8SHDocf022P
TWS7Gw9457KhweK5hYVSXG3bfEASgkpRReeIblq5bsTNcwaqAEi3AyfZR4EnjLfo
UU+49UAZ6UdQPp98FHhDl5zXlwrDfpQGGZfbPx8CggEAYZ3d89KMpBzgEjZYwKkZ
F2/2GsMVc0Pd4XG8TOzJb18d8bnLMd+fJ6Evckz7gZgtfiEPf/h8rqHb4yZnmlpZ
p9gjimekhiCcmsg24dSzO//otcj+bMDWILiJAWLrkou9OX1ASWa9AiRkKVIjRbQn
gjD6DCnybKanVH5ZnPjQLQ+Iz7e1FrTdd2JXTMZxYPyPUsZ2g6hRJcrX8z6eKubX
ygvQEoLvxh5ELPVd2OpDGHf78+IZtG++4OOozGMTHyyamADL/NkS4uhdRnuoyMPw
SgLlyGPZ/vwSFMO6uJGsUGaniTNu6BWooNnJSJ5SggFEKP7VqUzzJCy6T52fH75m
DwKCAQAcdLfGkl/ry9wEHKy9YUnCdkaBN2UHr0aOy/2UvCa+a4DsHTZnaQxpgr9X
TiScadSsSd/FYYtPxCzvg70j1QVp3uxa1NAebC6TU8VuRLCqXtaqA7GeK1t2Fa0J
0fDGuza7L5MbwGcTVF/CNSxUedxbNVaR6RrVUtPD5z7NrjOEOMuHyIdI2IunC+Ji
XTx3M079NX6F+dG/eW1ahkcGfk+qYcDhdOdZCfRyj9zby9IYN/DJj2qPwBo8YLYn
TbKtTjWTLVhdIAxImE/Ge7Vbs7vrfQSYyCZBDxRlQzBbPLazQLEP/0ZfUlBExUFj
Rr2zOczJ9RzGkaZMfrDoD2a8A5MS
-----END PRIVATE KEY-----
"""

PBKEY = """-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyCFzq7OZwwbenzlVkvI6
jwMfr0lwzrZllU1OJM0qyFYBXuc01wtN3n3PHNfAwlre84qesyNZ4evBiaostgEa
z3bTyjO/kdwxnPj1bnVtULQrwFPStQDtiVZCIV4kXTOAqyQUi1oZCEw9MnCgv/uO
am1VURaWPAd1zKKSlIdbWh2sY8zUbvW7WRlYbcNO6SAroUKNGzLjLXYpT/7BRrCr
lgEBHnLjey+Vhx3LbGFOXILp7R20SgTDJ8Aw4rnacftNGXqM9FAFC8WMeR4kqvv5
EDr8fe6QZOMLTYeXTdW6QhWCafmxN6Uwk+Fc3OKHBcDoWm49rrazE26ED9D6ytjJ
RTAkjktEdaCvVoiVhzzRekXcDcYPOEq2KwS6tBqUOMdR0sGpNBn/yFlx42vxU1su
CUpEfQ5i+IWGkG+2H95lF0Gz/bjUfNxUmEIZCX4ARUfd3CJKob0v9pvNaJSQVIe7
8JbXjL3YsI910YNK1lTBb1bH89gPWk3EqUvFudvaIqUVMsvlA/JP9S6TseD7O32C
GMTwb1vUKQUZZIPVj+wqP+u+Li9uvkmsjQOVTIdiNI/kVDwoWEgcCRial9r7RBW3
Ji0zTMymqPpMpuU876i4znAkWo65mwhJgox0DLcarjzhT+rvkcVyH4EX1R59s5Ws
tBB863N6A5itAmpdv4ONodECAwEAAQ==
-----END PUBLIC KEY-----
"""

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
#     'REFRESH_TOKEN_LIFETIME': timedelta(minutes=90),
#     'ROTATE_REFRESH_TOKENS': True,
#     'BLACKLIST_AFTER_ROTATION': True,
#     'UPDATE_LAST_LOGIN': True,
#     # 'ALGORITHM': 'HS256',
#     # 'SIGNING_KEY': SECRET_KEY,
#     # 'VERIFYING_KEY': None,
#     'ALGORITHM': 'RS256',
#     'SIGNING_KEY': PKEY,
#     'VERIFYING_KEY': PBKEY,
#     'AUDIENCE': None,
#     'ISSUER': None,
#     'JWK_URL': None,
#     'LEEWAY': 0,

#     'AUTH_HEADER_TYPES': ('Bearer',),
#     'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
#     'USER_ID_FIELD': 'id',
#     'USER_ID_CLAIM': 'user_id',
#     'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

#     'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
#     'TOKEN_TYPE_CLAIM': 'token_type',
#     'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

#     'JTI_CLAIM': 'jti',

#     'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
#     'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
#     'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
# }

CSRF_TRUSTED_ORIGINS = ['http://djangoproject.localhost/', 'http://127.0.0.1:8000']

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ORIGIN_WHITELIST = ['http://localhost:3000']

# /var/log/apache2/error.log
REDIS = redis.Redis(host='localhost', port=6379, db=0)

AUTH_USER_MODEL = 'api.CustomUser'
